name: Deploy on self-host runner

#sẽ trigger cái job này khi đẩy code lên nhánh nào: => đẩy code lên main thì tự trigger
on:
  push:
    branches:
      - master
      
#những công việc mà no sẽ khi push code
jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    #tải code về vps
    - name: Checkout code
      uses: actions/checkout@v3 
    #build tại vps bằng docker thì sau đó con backend sẽ chạy ở docker trong vps
    - name: Run `docker compose`
      run: docker compose -f compose.yaml up --build -d
    - name: Show Docker Compose logs
      run: docker compose logs
